// Text (English + Thai) and sample data for the Accident Hotspots admin page.
// Sample data is NOT from the database.
import type { Locale } from "./i18n";

const en = {
  htmlLang: "en",
  title: "Future Risk Hotspots",
  subtitle:
    "Shows locations with frequent accidents, based on traffic reports, hospital records, and map data.",
  lastUpdated: "Last Updated",
  synced: "Data Synchronized",
  loadError: "Cannot load data. Please check that the API server is running.",
  sample: "Sample data",
  high: "High",
  medium: "Medium",
  low: "Low",
  critical: "Critical",
  legend: "Legend:",
  activeFilter: "Active Filter",
  weather: "Weather: Rain/Wet Fog",
  surface: "Surface: Wet Asphalt",
  lighting: "Lighting: Dusk/Night",
  severity: (n: number) => `Severity: High&Critical (${n} Active)`,
  empty: "No hotspots match the active filters.",
  secB: "SECTION B • FUTURE RISK AREAS",
  hotspotNo: (n: number, level: string) => `Hotspot #${n} • ${level} Risk`,
  riskScore: (n: number) => `Risk Score: ${n} / 100`,
  confidence: (n: string) => `CONFIDENCE: ${n}%`,
  predictedPeriod: "Predicted Period:",
  keyFactors: "Key Risk Factors",
  factors: [
    "Bright evening sunlight around 4:45–5:30 PM",
    "Lots of students crossing after class around 4:15 PM",
    "Slippery road conditions in the evening",
  ],
  cluster: (n: number) => `Cluster #HS-${String(n).padStart(2, "0")}`,
  sector: "Sector B-3 (Central Quad)",
  totalIncidents: "TOTAL INCIDENTS",
  vsQ2: (n: number) => `+${n} vs Q2`,
  casualties: "CASUALTIES",
  casualtiesNote: (f: number, s: number) => `${f} Fat / ${s} Sev`,
  vector: "PRIMARY VECTOR",
  vectorValue: "Ped vs E-Scooter",
  recorded: (n: number) => `${n}% recorded`,
  env: "DOMINANT ENV",
  envValue: "Dusk/Night",
  envNote: (n: number) => `${n}% Wet Asphalt`,
  log: "RECENT INCIDENT LOG",
  viewTotal: (n: number) => `View ${n} Total`,
  vehiclePairs: ["Sedan vs. E-Scooter", "University Shuttle vs. Cyclist", "Motorcycle vs. Pedestrian"],
  injuries: { mod: "1 Mod Injury", minor: "1 Minor" } as Record<string, string>,
  recommended: "RECOMMENDED INTERVENTIONS",
  recommendedText:
    "Deploy illuminated pedestrian bollards and initiate smart signal retiming between 18:00 and 22:30 during precipitation events.",
  deploy: "Deploy Tactical Unit / Escort",
  deployed: "Request sent (demo only, nothing was dispatched).",
};

const th: typeof en = {
  htmlLang: "th",
  title: "จุดเสี่ยงในอนาคต",
  subtitle: "แสดงสถานที่ที่เกิดอุบัติเหตุบ่อย จากรายงานจราจร บันทึกโรงพยาบาล และข้อมูลแผนที่",
  lastUpdated: "อัปเดตล่าสุด",
  synced: "ซิงก์ข้อมูลแล้ว",
  loadError: "โหลดข้อมูลไม่ได้ กรุณาตรวจสอบว่าเซิร์ฟเวอร์ API ทำงานอยู่",
  sample: "ข้อมูลตัวอย่าง",
  high: "สูง",
  medium: "ปานกลาง",
  low: "ต่ำ",
  critical: "วิกฤต",
  legend: "คำอธิบาย:",
  activeFilter: "ตัวกรองที่ใช้",
  weather: "สภาพอากาศ: ฝน/หมอกชื้น",
  surface: "ผิวถนน: แอสฟัลต์เปียก",
  lighting: "แสงสว่าง: พลบค่ำ/กลางคืน",
  severity: (n: number) => `ความรุนแรง: สูงและวิกฤต (ใช้งาน ${n})`,
  empty: "ไม่มีจุดเสี่ยงที่ตรงกับตัวกรองที่เลือก",
  secB: "ส่วน B • พื้นที่เสี่ยงในอนาคต",
  hotspotNo: (n: number, level: string) => `จุดเสี่ยง #${n} • เสี่ยง${level}`,
  riskScore: (n: number) => `คะแนนความเสี่ยง: ${n} / 100`,
  confidence: (n: string) => `ความเชื่อมั่น: ${n}%`,
  predictedPeriod: "ช่วงเวลาที่พยากรณ์:",
  keyFactors: "ปัจจัยเสี่ยงสำคัญ",
  factors: [
    "แสงอาทิตย์ช่วงเย็นจ้าประมาณ 16:45–17:30 น.",
    "นักศึกษาข้ามถนนจำนวนมากหลังเลิกเรียนประมาณ 16:15 น.",
    "ผิวถนนลื่นในช่วงเย็น",
  ],
  cluster: (n: number) => `กลุ่ม #HS-${String(n).padStart(2, "0")}`,
  sector: "ภาค B-3 (ลานกลาง)",
  totalIncidents: "เหตุการณ์ทั้งหมด",
  vsQ2: (n: number) => `+${n} เทียบไตรมาส 2`,
  casualties: "ผู้ประสบเหตุ",
  casualtiesNote: (f: number, s: number) => `เสียชีวิต ${f} / สาหัส ${s}`,
  vector: "รูปแบบการชนหลัก",
  vectorValue: "คนเดินเท้า ชน สกู๊ตเตอร์ไฟฟ้า",
  recorded: (n: number) => `บันทึก ${n}%`,
  env: "สภาพแวดล้อมหลัก",
  envValue: "พลบค่ำ/กลางคืน",
  envNote: (n: number) => `แอสฟัลต์เปียก ${n}%`,
  log: "บันทึกเหตุการณ์ล่าสุด",
  viewTotal: (n: number) => `ดูทั้งหมด ${n}`,
  vehiclePairs: ["เก๋ง ชน สกู๊ตเตอร์ไฟฟ้า", "รถรับส่งมหาวิทยาลัย ชน จักรยาน", "จักรยานยนต์ ชน คนเดินเท้า"],
  injuries: { mod: "บาดเจ็บปานกลาง 1", minor: "บาดเจ็บเล็กน้อย 1" },
  recommended: "มาตรการที่แนะนำ",
  recommendedText:
    "ติดตั้งเสาไฟส่องสว่างสำหรับคนเดินเท้า และปรับจังหวะสัญญาณไฟอัจฉริยะระหว่าง 18:00 ถึง 22:30 น. ในช่วงที่ฝนตก",
  deploy: "ส่งหน่วยปฏิบัติการ / ผู้ติดตาม",
  deployed: "ส่งคำขอแล้ว (เดโมเท่านั้น ไม่มีการส่งหน่วยจริง)",
};

export const hotspotsText: Record<Locale, typeof en> = { en, th };

export const HOTSPOT_LOG = [
  { id: "INC-2026-884", when: "2026-10-04T18:42:00+07:00", pair: 0, injury: "mod" },
  { id: "INC-2026-862", when: "2026-10-01T19:15:00+07:00", pair: 1, injury: "minor" },
  { id: "INC-2026-855", when: "2026-09-29T17:20:00+07:00", pair: 2, injury: "mod" },
  { id: "INC-2026-841", when: "2026-09-26T18:05:00+07:00", pair: 0, injury: "minor" },
  { id: "INC-2026-838", when: "2026-09-24T19:40:00+07:00", pair: 1, injury: "minor" },
  { id: "INC-2026-830", when: "2026-09-22T17:55:00+07:00", pair: 2, injury: "mod" },
];
